development: &dev_dws
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: trenti
  pool: 5
  username: trenti
  password: eseadri92

test:
  <<: *dev_dws

production:
  <<: *dev_dws
  #host: mbox2.punsset.com
  #port: 54320
